# Generated by Django 5.0.3 on 2024-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Названия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('team_quantity', models.IntegerField(verbose_name='Количество участников')),
            ],
        ),
    ]
