# Generated by Django 5.0.4 on 2024-04-06 10:29

from django.db import migrations


def fill_decription(apps, schema_editor):
    Project = apps.get_model('app', 'Project')
    Project.objects.create(
        name='LaLaLa',
        description="Наша игра разработана через RPG Maker ХP. "
                    "Это программа, позволяющая вам создать оригинальную "
                    "ролевую игру без каких-либо специальных знаний и подготовки. "
                    "Различные функции RPG MAKER XP, от параметров персонажа до "
                    "боевой системы, создаются с помощью программ, называемых скриптами. "
                    "RPG MAKER XP оснащен системой сценариев игр Ruby (RGSS), основанной на "
                    "языке Ruby и настроенной специально для этой программы.",
        team_quantity=5
    )


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [migrations.RunPython(fill_decription)]
